# Add the following lines to your application.properties or application.yml file

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: none
  application:
    name: user-service
  http:
    server:
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: Content-Type
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    '[org.springframework.cloud.gateway]': TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE





