server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: none
  application:
    name: inventory-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
