spring:
  main:
    web-application-type: reactive
  mvc:
    cors:
      enabled: true
    jackson:
      serialization:
        fail-on-empty-beans: false


  # CORS Configuration
  cors:
    allowed-origins:
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
    exposed-headers: [ ]
    allow-credentials: true
    max-age: 3600
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/product-service/**
        - id: ORDER-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/order-service/**
        - id: INVENTORY-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/inventory-service/**
server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    '[org.springframework.cloud.gateway]': TRACE
